# Generated by Django 4.2.1 on 2023-05-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_account_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='expences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.expense'),
        ),
        migrations.AddField(
            model_name='account',
            name='incomes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.income'),
        ),
    ]
