# Generated by Django 4.2.1 on 2023-05-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_expense_account_remove_income_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='expences',
        ),
        migrations.RemoveField(
            model_name='account',
            name='incomes',
        ),
    ]
