# Generated by Django 4.2.1 on 2023-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
